- {name: 'work', url: '/work'}
- {name: 'visualizations', url: '/visualizations'}

social:
- {icon: 'github', link: 'https://github.com/aylinko'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/akosar'}
