
- {name: 'publications', url: '/publications'}
- {name: 'work', url: '/work'}
- {name: 'visualizations', url: '/visualizations'}
- {name: 'temp', url: '/temp'}

social:
- {icon: 'github', link: 'https://github.com/aylinko'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/akosar'}
