menu:
- {name: 'work', url: '/work'}
- {name: 'visualizations', url: '/visualizations'}
- {name: 'samples', url: '/samples'}
- {name: 'photography', url: '/photography'}

social:
- {icon: 'github', link: 'https://github.com/aylinko'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/akosar'}
